### PR TITLE
Add support for more 8188CUS and 8192CUS devices

### PR DESCRIPTION
**Pull request by oblique**
I found the patch from here: https://aur.archlinux.org/packages/8192cu-dkms

### CODE REVIEW

**Comment by pvaret** [comment]
Hi! Thank you for the patch. I'm a little unsure about adding support for devices I can't test, but I suppose that if someone is using this driver then their device probably is already not working well anyway, so at worst it will keep not working...

**Comment by EoflaOE** [comment]
Thanks for bringing up more support for RTL8188CUS and 8192CUS drives! It now made D-Link DWA-121 Wireless N 150 Pico Adapter work correctly!

**Comment by pvaret** [comment]
Cool, thanks for letting me know! :)

**Comment by EoflaOE** [comment]
You are welcome

**Pull request merged**
