### PR TITLE
Add Raspberry Pi Platform

### PR DESCRIPTION
**Pull request by dwardor**
Modifications to add raspberry pi platform.
Tested on my pis (1 2 and 3)

### CODE REVIEW

**Comment by dlech** [comment]
Since the official Raspberry Pi kernels already includes this driver, I am wondering who this would be useful for?

**Comment by dwardor** [comment]
OSMC kernel does not include the module so I build it myself

**Comment by dlech** [comment]
Got it. It looks like there is nothing actually specific about Raspberry Pi in the config. Maybe we should call it `CONFIG_PLATFORM_ARM_GENERIC` instead?

**Comment by dwardor** [comment]
I actually just copied the additions from https://github.com/cilynx/rtl88x2bu.git

**Comment by dlech** [comment]
OK, I went ahead and made the changed and merged. Thanks!

**Comment by dwardor** [comment]
Thanks !

**Pull request merged**
