### PR TITLE
I test with an WN822N device and works great

### PR DESCRIPTION
**Pull request by allanmfz**

### CODE REVIEW

**Comment by dlech** [comment]
What is output of `lsusb` for this device? We haven't been doing this, but we should be adding the USB vendor and product id in this list.

**Comment by allanmfz** [comment]
Bus 003 Device 002: ID 0bda:8178 Realtek Semiconductor Corp. RTL8192CU
802.11n WLAN Adapter




Atenciosamente,

Allan Maia Fernandes
Frontend/Backend Developer

+55 (11) 9 6581 4709 <+5511965814709>
LinkedIn <https://www.linkedin.com/in/allan-maia-fernandes-ba4a289a>

[image: Magento Certified Frontend Developer]
<https://www.magentocommerce.com/certification/directory/dev/1855740/>

2016-05-04 12:42 GMT-03:00 David Lechner <notifications@github.com>:

**Comment by dlech** [comment]
Thanks. Can you modify this pull request to say 

    TP-Link TL-WN822N (0bda:8178)

instead of just 

    TP-Link TL-WN822N

**Comment by allanmfz** [comment]
Done!

**Comment by dlech** [comment]
Thanks!

**Pull request merged**
