### PR TITLE
Update CI to last mainline and LTS version

### PR DESCRIPTION
**Pull request by CGarces**
Upgraded build environment to Xenial

### CODE REVIEW

**Comment by CGarces** [comment]
note that #156 should fix the builds error over 5.2-rc1

**Comment by dlech** [comment]
It might be nice to leave 4.15 in for another year since that is what Ubuntu 18.04 LTS runs.

**Comment by CGarces** [comment]
Hi @dlech 
I use 4.19.45 because is the last LTS at https://www.kernel.org/ 

The initial motivation of this script was testing the compilation on the different kernels used by LibreElec, and is not focused on Ubuntu.

BTW the kernel 3.14 is used by legacy AmLogic kernels, I'll drop it soon. I think that use last _official_ LTS and mainline is enough.

**Comment by pvaret** [comment]
Carlos, thanks a bunch for the PR. :)

What's the cost of keeping 4.15 tests around a bit longer? If it's just another entry in the Travis configuration, I'd rather keep it, as this repo does concern itself primarily with Ubuntu support. On the other hand, if 4.15 requires some tricky dedicated set up, I'm fine dropping it, provided that the code itself does not drop support for older kernels.

**Comment by CGarces** [comment]
@pvaret 
It's very easy just copy&paste from 4.19 and change the version numbers to match with the ones at kernel.org (i can't do it right now).

**Comment by pvaret** [comment]
Ok, fair enough. I'll be offline for a little while, but do send the PR to do that, I'll approve it as soon as I can.

**Pull request merged**
