### PR TITLE
Tested on TL-WN821N

### PR DESCRIPTION
**Pull request by deksar**
Used with TL-WN821N, tested on CentOS 6.8, unstable internet connection&disconnection problem resolved!

### CODE REVIEW

**Comment by dlech** [comment]
Could you please post the output of `lsusb` here for future reference and add the VID:PID in the readme like some of the other entries?

**Comment by CGarces** [comment]
The id is already supported

`Bus 001 Device 002: ID 0bda:8178 Realtek Semiconductor Corp. RTL8192CU 802.11n WLAN Adapter
`
That match with https://github.com/pvaret/rtl8192cu-fixes/blob/master/os_dep/linux/usb_intf.c#L90

See [this post] (https://forums.linuxmint.com/viewtopic.php?f=49&t=159484) for reference.

**Comment by pvaret** [comment]
Thanks for the report. Device information added in a separate commit.

**Comment by monolifed** [comment]
This worked great for the same adapter (also the same id string) on Debian. I tried rtl8xxxu after seeing the commit about it. It didn't work at all.

**Comment by pvaret** [comment]
You need to un-blacklist rtl8xxxu in order to try it out and (I think) actually blacklist rtl8192cu, which otherwise still gets used preferentially by the kernel. It also probably depends on which kernel version you are running, though.

**Comment by monolifed** [comment]
I commented out `install rtl8xxxu /bin/false` in `blacklist-native-rtl8192.conf`, issued `dkms uninstall 8192cu/1.10` and `dkms remove 8192cu/1.10`. My kernel was 4.13 at the time.
Since I couldn't find the steps for removal, I am not sure if these are the right steps or not.

**Comment by pvaret** [comment]
Yep, that's the proper way to uninstall this driver. You can just delete `blacklist-native-rtl8192.conf`, for that matter.

**Pull request closed without merging**
