### PR TITLE
Migrate travis CI to github actions

### PR DESCRIPTION
**Pull request by CGarces**
travis-ci.org will be shutting down and travis-ci.com not looks like a valid replacement.

Migrated automated CI to Github actions.

The build test all kerners at kernel.org and compile using the available GCC compiler on the last Ubuntu image provided by Github Actions.

### CODE REVIEW

**Comment by dlech** [comment]
What is the issue with travis-ci.com? From what I read, it is still free for open source projects.

**Comment by CGarces** [comment]
By default public repositories are building against your credits.

As I read at:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> _"We will be offering an allotment of OSS minutes that will be reviewed and allocated on a **case by case** basis"_

I'm not sure about the process the post at Travis blog not is clear to me, faq not helps

https://docs.travis-ci.com/user/billing-faq/

> _Each of the Travis CI Plans can have an amount of special OSS credits per month assigned to run builds only on public repositories. To find out more about it please contact the Travis CI support team._


My current plan only provide 10000 Credits and not are renewed monthly, and 0 OSS credits. Not looks easy to get the OSS credits.

https://travis-ci.community/t/oss-only-credits-request-processing-time-estimate/10446

Unless someone clarify the status of Travis builds on public repositories I prefer start using Github Actions.

Off course this PR is not urgent you can keep it on hold.

**Comment by CGarces** [comment]
Opps.

Works fine on Ubuntu 18.04.5 https://github.com/CGarces/rtl8192cu-fixes/actions/runs/436380312
But fails on Ubuntu 20.04.1 https://github.com/jwrdegoede/rtl8189ES_linux/runs/1594787833?check_suite_focus=true

Package libssl1.0.0 is not installed.

If you merge this PR probably Github will use  20.04.1 for  `runs-on: ubuntu-latest`

I'll check the error and set to 18.04 if I can't fix it. 
Please don't merge.

**Comment by CGarces** [comment]
Ready to merge.

The dependencies are different between kernels.

Depends: linux-headers-4.4.248-0404248, libc6 (>= 2.14), **libssl1.0.0** (>= 1.0.0)
Depends: linux-headers-5.10.0-051000,   libc6 (>= 2.14), **libssl1.1**   (>= 1.1.0), libelf1 (>= 0.142)

`sudo dpkg --force-all -i *.deb` allow to test the build of kernel 4.4 with libssl1.1 instead of libssl1.0.0.

**Comment by pvaret** [comment]
Thanks!

**Comment by pvaret** [comment]
I reverted the merge: it broke the build. See https://github.com/pvaret/rtl8192cu-fixes/actions/runs/454741110. Can you fix and resubmit please?

**Comment by CGarces** [comment]
Hi @pvaret 

The script itself, works. The problem is the .deb files used by the script.

See https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11-rc1/

"amd64/build failed "

Note that Travis Ci builds will fail for 5.11-rc for the same reason so the revert will not fox any problem, just hide it (because travis build not are executed).

I'm trying to fix adding code to test if both .deb files exists and skip the build but not is working on a first approach.

Something like:

if [ -f "$ALL_DEB" -a -f "$ARCH_DEB" ]; then

See https://github.com/CGarces/rtl8192eu-linux-driver/actions/runs/451092173/workflow#L37

But always goes through the "else" part.

I'm sure that is some trivial error with the bash, but I don't have time to fix it now.

**Comment by CGarces** [comment]
Opps, I was partially wrong, travis builds are executed (but https://travis-ci.org/ will be shut down)

See for example

https://travis-ci.org/github/pvaret/rtl8192cu-fixes/jobs/749151266#L226

It's trying to get the deb file from 
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.14/

And fails due the same problem "Test amd64/build failed", the .deb file not exist.

**Pull request merged**
