### PR TITLE
kernel-5.1-rc1 fix

### PR DESCRIPTION
**Pull request by MilhouseVH**
https://github.com/torvalds/linux/commit/736706bee3298208343a76096370e4f6a5c55915

### CODE REVIEW

**Comment by pvaret** [comment]
Hey, thank you kindly for the PR. :)

**Comment by pvaret** [comment]
@MilhouseVH, over the last year you've submitted a number of solid PRs to keep this driver compatible with the latest kernels, and while I believe I've mentioned being ambivalent about keeping this project going when rtl8xxxu exists and should focus efforts, it's been really helpful to a bunch of people, which matters too. As such, would you like commit access to this repo?

(Ping additional contributor @dlech as PSA.)

**Comment by MilhouseVH** [comment]
> As such, would you like commit access to this repo?

Sure, that might help save some time, thanks.

**Comment by pvaret** [comment]
Excellent, thank you! I just sent you an invite, you should be able to see it here: https://github.com/pvaret/rtl8192cu-fixes/invitations.

**Pull request merged**
